version: '2'
services:
    latency_db:
        image: 'postgres:9.5'
        environment:
            POSTGRES_DB: 'latency'
        ports:
            - 5432:5432
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
