version: '2'
services:
    db:
        image: 'postgres:9.6'
        environment:
            POSTGRES_DB: ci
            POSTGRES_USER: app_user
            POSTGRES_PASSWORD: app-user-password
        restart: always
        ports:
            - 5438:5432

    me:
        build: .
        links:
            - db
        environment:
          PGUSER: app_user
          PGPASSWORD: app-user-password
          PGDATABASE: ci
          PGHOST: db
        ports:
          - 1234:1234

    misc:
        build: .
        command: /opt/latency/python/latency.py
        environment:
          - PGUSER
          - PGPASSWORD
          - PGDATABASE
          - PGHOST
        ports:
          - 1234:1234
