CREATE SCHEMA if not exists latency;

GRANT USAGE ON SCHEMA latency TO doorman;

ALTER DEFAULT PRIVILEGES IN SCHEMA latency 
    GRANT SELECT, INSERT ON TABLES TO doorman;

ALTER DEFAULT PRIVILEGES IN SCHEMA latency
    GRANT EXECUTE ON FUNCTIONS TO doorman;
